
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.galaxycore.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.galaxycore.item.VolcanicOreItem;
import net.mcreator.galaxycore.item.VolcanicBladeItem;
import net.mcreator.galaxycore.item.VolcanicAxeItem;
import net.mcreator.galaxycore.item.VibrantAlloyItem;
import net.mcreator.galaxycore.item.VanguardSwordItem;
import net.mcreator.galaxycore.item.VanguardPickaxeItem;
import net.mcreator.galaxycore.item.VanguardIngotItem;
import net.mcreator.galaxycore.item.VanguardAxeItem;
import net.mcreator.galaxycore.item.TrebolItem;
import net.mcreator.galaxycore.item.TransmisorItem;
import net.mcreator.galaxycore.item.TokenItem;
import net.mcreator.galaxycore.item.SuperSemillaItem;
import net.mcreator.galaxycore.item.SuperCacaItem;
import net.mcreator.galaxycore.item.StellarAlloyItem;
import net.mcreator.galaxycore.item.StarlightItem;
import net.mcreator.galaxycore.item.SoulariumItem;
import net.mcreator.galaxycore.item.SkullyellowItem;
import net.mcreator.galaxycore.item.SkullredItem;
import net.mcreator.galaxycore.item.SkullpurpleItem;
import net.mcreator.galaxycore.item.SkullgreyItem;
import net.mcreator.galaxycore.item.SkullgreenItem;
import net.mcreator.galaxycore.item.SkullbrownItem;
import net.mcreator.galaxycore.item.SkullblueItem;
import net.mcreator.galaxycore.item.SemillaItem;
import net.mcreator.galaxycore.item.SandwichitoItem;
import net.mcreator.galaxycore.item.RedstoneAlloyNuggetItem;
import net.mcreator.galaxycore.item.RedstoneAlloyItem;
import net.mcreator.galaxycore.item.PlanosItem;
import net.mcreator.galaxycore.item.PepitaVibranteItem;
import net.mcreator.galaxycore.item.PepitaPulsanteItem;
import net.mcreator.galaxycore.item.PepitaEstelarItem;
import net.mcreator.galaxycore.item.PepitaEnergeticaItem;
import net.mcreator.galaxycore.item.PepitaDeMegaEstrellaItem;
import net.mcreator.galaxycore.item.PepitaDeAlmasItem;
import net.mcreator.galaxycore.item.PepitaConductoraItem;
import net.mcreator.galaxycore.item.PatricioEstrellaItem;
import net.mcreator.galaxycore.item.PanchitoItem;
import net.mcreator.galaxycore.item.OrbeyellowItem;
import net.mcreator.galaxycore.item.OrberedItem;
import net.mcreator.galaxycore.item.OrbepurpleItem;
import net.mcreator.galaxycore.item.OrbegreyItem;
import net.mcreator.galaxycore.item.OrbegreenItem;
import net.mcreator.galaxycore.item.OrbebrownItem;
import net.mcreator.galaxycore.item.OrbeblueItem;
import net.mcreator.galaxycore.item.MunecoDePajaItem;
import net.mcreator.galaxycore.item.MonsterEnergyItem;
import net.mcreator.galaxycore.item.MonedaItem;
import net.mcreator.galaxycore.item.MiniReactorItem;
import net.mcreator.galaxycore.item.MiniPortalItem;
import net.mcreator.galaxycore.item.MelodicAlloyNuggetItem;
import net.mcreator.galaxycore.item.MelodicAlloyItem;
import net.mcreator.galaxycore.item.McCacoItem;
import net.mcreator.galaxycore.item.LingoteNeutralTier1Item;
import net.mcreator.galaxycore.item.KnightsSwordItem;
import net.mcreator.galaxycore.item.KeyVerdeItem;
import net.mcreator.galaxycore.item.KeyRosaItem;
import net.mcreator.galaxycore.item.KeyRojoItem;
import net.mcreator.galaxycore.item.KeyMoradaItem;
import net.mcreator.galaxycore.item.KeyMaderaItem;
import net.mcreator.galaxycore.item.KeyAmarillaItem;
import net.mcreator.galaxycore.item.IronheartSwordItem;
import net.mcreator.galaxycore.item.InfinityswordbalancedItem;
import net.mcreator.galaxycore.item.Infinitysword1Item;
import net.mcreator.galaxycore.item.Infinity1pickItem;
import net.mcreator.galaxycore.item.HubItem;
import net.mcreator.galaxycore.item.Hub4Item;
import net.mcreator.galaxycore.item.Hub3Item;
import net.mcreator.galaxycore.item.Hub2Item;
import net.mcreator.galaxycore.item.Hub1Item;
import net.mcreator.galaxycore.item.HierroPulsanteItem;
import net.mcreator.galaxycore.item.HierroConductorItem;
import net.mcreator.galaxycore.item.HellfireSwordItem;
import net.mcreator.galaxycore.item.HellfirePickaxeItem;
import net.mcreator.galaxycore.item.HeartyellowItem;
import net.mcreator.galaxycore.item.HeartredItem;
import net.mcreator.galaxycore.item.HeartpurpleItem;
import net.mcreator.galaxycore.item.HeartgreyItem;
import net.mcreator.galaxycore.item.HeartgreenItem;
import net.mcreator.galaxycore.item.HeartbrownItem;
import net.mcreator.galaxycore.item.HeartblueItem;
import net.mcreator.galaxycore.item.GuanteleteItem;
import net.mcreator.galaxycore.item.GoldenBladeItem;
import net.mcreator.galaxycore.item.FrozenBladeItem;
import net.mcreator.galaxycore.item.FlamepurpleItem;
import net.mcreator.galaxycore.item.EnergeticAlloyItem;
import net.mcreator.galaxycore.item.EnderiumBaseItem;
import net.mcreator.galaxycore.item.EndSteelNuggetItem;
import net.mcreator.galaxycore.item.EndSteelAlloyItem;
import net.mcreator.galaxycore.item.ElectricalsteelIngotItem;
import net.mcreator.galaxycore.item.ElectricalSteelNuggetItem;
import net.mcreator.galaxycore.item.DoritosItem;
import net.mcreator.galaxycore.item.DarkSteelNuggetItem;
import net.mcreator.galaxycore.item.DarkSteelItem;
import net.mcreator.galaxycore.item.CombustibleRadiactivoItem;
import net.mcreator.galaxycore.item.CoinsilverItem;
import net.mcreator.galaxycore.item.CoinGoldItem;
import net.mcreator.galaxycore.item.CofrecitoItem;
import net.mcreator.galaxycore.item.CatalizadorItem;
import net.mcreator.galaxycore.item.CalaveraOscuraItem;
import net.mcreator.galaxycore.item.CajitaFelizItem;
import net.mcreator.galaxycore.item.CacotaItem;
import net.mcreator.galaxycore.item.BuscadorDelUniversoItem;
import net.mcreator.galaxycore.item.BrujulaMalditaItem;
import net.mcreator.galaxycore.item.BraveheartpickaxeItem;
import net.mcreator.galaxycore.item.BraveheartSwordItem;
import net.mcreator.galaxycore.item.BraveheartItem;
import net.mcreator.galaxycore.item.BraveheartAxeItem;
import net.mcreator.galaxycore.item.AntiMateriaItem;
import net.mcreator.galaxycore.item.AmethystStarlightItem;
import net.mcreator.galaxycore.item.AlmaDeDragonItem;
import net.mcreator.galaxycore.item.AgujeroNegroItem;
import net.mcreator.galaxycore.item.AbsolutePlateItem;
import net.mcreator.galaxycore.GalaxyCoreMod;

public class GalaxyCoreModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, GalaxyCoreMod.MODID);
	public static final RegistryObject<Item> STARLIGHT = REGISTRY.register("starlight", () -> new StarlightItem());
	public static final RegistryObject<Item> AMETHYST_STARLIGHT = REGISTRY.register("amethyst_starlight", () -> new AmethystStarlightItem());
	public static final RegistryObject<Item> CAJITA_FELIZ = REGISTRY.register("cajita_feliz", () -> new CajitaFelizItem());
	public static final RegistryObject<Item> MONSTER_ENERGY = REGISTRY.register("monster_energy", () -> new MonsterEnergyItem());
	public static final RegistryObject<Item> SANDWICHITO = REGISTRY.register("sandwichito", () -> new SandwichitoItem());
	public static final RegistryObject<Item> DORITOS = REGISTRY.register("doritos", () -> new DoritosItem());
	public static final RegistryObject<Item> GUANTELETE = REGISTRY.register("guantelete", () -> new GuanteleteItem());
	public static final RegistryObject<Item> GOLDEN_BLADE = REGISTRY.register("golden_blade", () -> new GoldenBladeItem());
	public static final RegistryObject<Item> HUB_2 = REGISTRY.register("hub_2", () -> new Hub2Item());
	public static final RegistryObject<Item> HUB = REGISTRY.register("hub", () -> new HubItem());
	public static final RegistryObject<Item> HUBGREEN = REGISTRY.register("hubgreen", () -> new Hub3Item());
	public static final RegistryObject<Item> HUB_4 = REGISTRY.register("hub_4", () -> new Hub4Item());
	public static final RegistryObject<Item> HUB_1 = REGISTRY.register("hub_1", () -> new Hub1Item());
	public static final RegistryObject<Item> SEXY_XD = block(GalaxyCoreModBlocks.SEXY_XD);
	public static final RegistryObject<Item> PANCHITO = REGISTRY.register("panchito", () -> new PanchitoItem());
	public static final RegistryObject<Item> CATALIZADOR = REGISTRY.register("catalizador", () -> new CatalizadorItem());
	public static final RegistryObject<Item> BRUJULA_MALDITA = REGISTRY.register("brujula_maldita", () -> new BrujulaMalditaItem());
	public static final RegistryObject<Item> CALAVERA_OSCURA = REGISTRY.register("calavera_oscura", () -> new CalaveraOscuraItem());
	public static final RegistryObject<Item> AGUJERO_NEGRO = REGISTRY.register("agujero_negro", () -> new AgujeroNegroItem());
	public static final RegistryObject<Item> ALMA_DE_DRAGON = REGISTRY.register("alma_de_dragon", () -> new AlmaDeDragonItem());
	public static final RegistryObject<Item> ANTI_MATERIA = REGISTRY.register("anti_materia", () -> new AntiMateriaItem());
	public static final RegistryObject<Item> COMBUSTIBLE_RADIACTIVO = REGISTRY.register("combustible_radiactivo", () -> new CombustibleRadiactivoItem());
	public static final RegistryObject<Item> PATRICIO_ESTRELLA = REGISTRY.register("patricio_estrella", () -> new PatricioEstrellaItem());
	public static final RegistryObject<Item> MINI_REACTOR = REGISTRY.register("mini_reactor", () -> new MiniReactorItem());
	public static final RegistryObject<Item> MINI_PORTAL = REGISTRY.register("mini_portal", () -> new MiniPortalItem());
	public static final RegistryObject<Item> PLANOS = REGISTRY.register("planos", () -> new PlanosItem());
	public static final RegistryObject<Item> PEPITA_DE_MEGA_ESTRELLA = REGISTRY.register("pepita_de_mega_estrella", () -> new PepitaDeMegaEstrellaItem());
	public static final RegistryObject<Item> TRANSMISOR = REGISTRY.register("transmisor", () -> new TransmisorItem());
	public static final RegistryObject<Item> SEMILLA = REGISTRY.register("semilla", () -> new SemillaItem());
	public static final RegistryObject<Item> SUPER_SEMILLA = REGISTRY.register("super_semilla", () -> new SuperSemillaItem());
	public static final RegistryObject<Item> MUNECO_DE_PAJA = REGISTRY.register("muneco_de_paja", () -> new MunecoDePajaItem());
	public static final RegistryObject<Item> BUSCADOR_DEL_UNIVERSO = REGISTRY.register("buscador_del_universo", () -> new BuscadorDelUniversoItem());
	public static final RegistryObject<Item> MONEDA = REGISTRY.register("moneda", () -> new MonedaItem());
	public static final RegistryObject<Item> SUPER_CACA = REGISTRY.register("super_caca", () -> new SuperCacaItem());
	public static final RegistryObject<Item> MC_CACO = REGISTRY.register("mc_caco", () -> new McCacoItem());
	public static final RegistryObject<Item> LINGOTE_NEUTRAL_TIER_1 = REGISTRY.register("lingote_neutral_tier_1", () -> new LingoteNeutralTier1Item());
	public static final RegistryObject<Item> HIERRO_PULSANTE = REGISTRY.register("hierro_pulsante", () -> new HierroPulsanteItem());
	public static final RegistryObject<Item> REDSTONE_ALLOY = REGISTRY.register("redstone_alloy", () -> new RedstoneAlloyItem());
	public static final RegistryObject<Item> ENERGETIC_ALLOY = REGISTRY.register("energetic_alloy", () -> new EnergeticAlloyItem());
	public static final RegistryObject<Item> VIBRANT_ALLOY = REGISTRY.register("vibrant_alloy", () -> new VibrantAlloyItem());
	public static final RegistryObject<Item> SOULARIUM = REGISTRY.register("soularium", () -> new SoulariumItem());
	public static final RegistryObject<Item> STELLAR_ALLOY = REGISTRY.register("stellar_alloy", () -> new StellarAlloyItem());
	public static final RegistryObject<Item> HIERRO_CONDUCTOR = REGISTRY.register("hierro_conductor", () -> new HierroConductorItem());
	public static final RegistryObject<Item> MELODIC_ALLOY = REGISTRY.register("melodic_alloy", () -> new MelodicAlloyItem());
	public static final RegistryObject<Item> DARK_STEEL = REGISTRY.register("dark_steel", () -> new DarkSteelItem());
	public static final RegistryObject<Item> END_STEEL_ALLOY = REGISTRY.register("end_steel_alloy", () -> new EndSteelAlloyItem());
	public static final RegistryObject<Item> ENDERIUM_BASE = REGISTRY.register("enderium_base", () -> new EnderiumBaseItem());
	public static final RegistryObject<Item> ELECTRICALSTEEL_INGOT = REGISTRY.register("electricalsteel_ingot", () -> new ElectricalsteelIngotItem());
	public static final RegistryObject<Item> PEPITA_PULSANTE = REGISTRY.register("pepita_pulsante", () -> new PepitaPulsanteItem());
	public static final RegistryObject<Item> PEPITA_ENERGETICA = REGISTRY.register("pepita_energetica", () -> new PepitaEnergeticaItem());
	public static final RegistryObject<Item> PEPITA_VIBRANTE = REGISTRY.register("pepita_vibrante", () -> new PepitaVibranteItem());
	public static final RegistryObject<Item> PEPITA_DE_ALMAS = REGISTRY.register("pepita_de_almas", () -> new PepitaDeAlmasItem());
	public static final RegistryObject<Item> PEPITA_ESTELAR = REGISTRY.register("pepita_estelar", () -> new PepitaEstelarItem());
	public static final RegistryObject<Item> PEPITA_CONDUCTORA = REGISTRY.register("pepita_conductora", () -> new PepitaConductoraItem());
	public static final RegistryObject<Item> MELODIC_ALLOY_NUGGET = REGISTRY.register("melodic_alloy_nugget", () -> new MelodicAlloyNuggetItem());
	public static final RegistryObject<Item> DARK_STEEL_NUGGET = REGISTRY.register("dark_steel_nugget", () -> new DarkSteelNuggetItem());
	public static final RegistryObject<Item> END_STEEL_NUGGET = REGISTRY.register("end_steel_nugget", () -> new EndSteelNuggetItem());
	public static final RegistryObject<Item> REDSTONE_ALLOY_NUGGET = REGISTRY.register("redstone_alloy_nugget", () -> new RedstoneAlloyNuggetItem());
	public static final RegistryObject<Item> HELLFIRESWORD = REGISTRY.register("hellfiresword", () -> new HellfireSwordItem());
	public static final RegistryObject<Item> HELLFIREPICKAXE = REGISTRY.register("hellfirepickaxe", () -> new HellfirePickaxeItem());
	public static final RegistryObject<Item> ELECTRICAL_STEEL_NUGGET = REGISTRY.register("electrical_steel_nugget", () -> new ElectricalSteelNuggetItem());
	public static final RegistryObject<Item> PRUEBAA = block(GalaxyCoreModBlocks.PRUEBAA);
	public static final RegistryObject<Item> COFRECITO = REGISTRY.register("cofrecito", () -> new CofrecitoItem());
	public static final RegistryObject<Item> IRONHEARTSWORD = REGISTRY.register("ironheartsword", () -> new IronheartSwordItem());
	public static final RegistryObject<Item> FROZENBLADE = REGISTRY.register("frozenblade", () -> new FrozenBladeItem());
	public static final RegistryObject<Item> KNIGHTSSWORD = REGISTRY.register("knightssword", () -> new KnightsSwordItem());
	public static final RegistryObject<Item> VOLCANICBLADE = REGISTRY.register("volcanicblade", () -> new VolcanicBladeItem());
	public static final RegistryObject<Item> VOLCANIC_ORE = REGISTRY.register("volcanic_ore", () -> new VolcanicOreItem());
	public static final RegistryObject<Item> VOLCANICAXE = REGISTRY.register("volcanicaxe", () -> new VolcanicAxeItem());
	public static final RegistryObject<Item> BLOQUE = block(GalaxyCoreModBlocks.BLOQUE);
	public static final RegistryObject<Item> KEY_ROJO = REGISTRY.register("key_rojo", () -> new KeyRojoItem());
	public static final RegistryObject<Item> KEY_AMARILLA = REGISTRY.register("key_amarilla", () -> new KeyAmarillaItem());
	public static final RegistryObject<Item> KEY_MADERA = REGISTRY.register("key_madera", () -> new KeyMaderaItem());
	public static final RegistryObject<Item> KEY_ROSA = REGISTRY.register("key_rosa", () -> new KeyRosaItem());
	public static final RegistryObject<Item> KEY_MORADA = REGISTRY.register("key_morada", () -> new KeyMoradaItem());
	public static final RegistryObject<Item> KEY_VERDE = REGISTRY.register("key_verde", () -> new KeyVerdeItem());
	public static final RegistryObject<Item> BRAVEHEART = REGISTRY.register("braveheart", () -> new BraveheartItem());
	public static final RegistryObject<Item> BRAVEHEARTPICKAXE = REGISTRY.register("braveheartpickaxe", () -> new BraveheartpickaxeItem());
	public static final RegistryObject<Item> BRAVEHEARTAXE = REGISTRY.register("braveheartaxe", () -> new BraveheartAxeItem());
	public static final RegistryObject<Item> BRAVEHEARTSWORD = REGISTRY.register("braveheartsword", () -> new BraveheartSwordItem());
	public static final RegistryObject<Item> VANGUARDSWORD = REGISTRY.register("vanguardsword", () -> new VanguardSwordItem());
	public static final RegistryObject<Item> VANGUARDPICKAXE = REGISTRY.register("vanguardpickaxe", () -> new VanguardPickaxeItem());
	public static final RegistryObject<Item> VANGUARDAXE = REGISTRY.register("vanguardaxe", () -> new VanguardAxeItem());
	public static final RegistryObject<Item> VANGUARDINGOT = REGISTRY.register("vanguardingot", () -> new VanguardIngotItem());
	public static final RegistryObject<Item> TOKEN = REGISTRY.register("token", () -> new TokenItem());
	public static final RegistryObject<Item> COINSILVER = REGISTRY.register("coinsilver", () -> new CoinsilverItem());
	public static final RegistryObject<Item> COIN_GOLD = REGISTRY.register("coin_gold", () -> new CoinGoldItem());
	public static final RegistryObject<Item> HEARTBLUE = REGISTRY.register("heartblue", () -> new HeartblueItem());
	public static final RegistryObject<Item> HEARTBROWN = REGISTRY.register("heartbrown", () -> new HeartbrownItem());
	public static final RegistryObject<Item> HEARTGREEN = REGISTRY.register("heartgreen", () -> new HeartgreenItem());
	public static final RegistryObject<Item> HEARTGREY = REGISTRY.register("heartgrey", () -> new HeartgreyItem());
	public static final RegistryObject<Item> HEARTPURPLE = REGISTRY.register("heartpurple", () -> new HeartpurpleItem());
	public static final RegistryObject<Item> HEARTRED = REGISTRY.register("heartred", () -> new HeartredItem());
	public static final RegistryObject<Item> HEARTYELLOW = REGISTRY.register("heartyellow", () -> new HeartyellowItem());
	public static final RegistryObject<Item> FLAMEPURPLE = REGISTRY.register("flamepurple", () -> new FlamepurpleItem());
	public static final RegistryObject<Item> ORBEBLUE = REGISTRY.register("orbeblue", () -> new OrbeblueItem());
	public static final RegistryObject<Item> ORBEBROWN = REGISTRY.register("orbebrown", () -> new OrbebrownItem());
	public static final RegistryObject<Item> ORBEGREEN = REGISTRY.register("orbegreen", () -> new OrbegreenItem());
	public static final RegistryObject<Item> ORBEGREY = REGISTRY.register("orbegrey", () -> new OrbegreyItem());
	public static final RegistryObject<Item> ORBEPURPLE = REGISTRY.register("orbepurple", () -> new OrbepurpleItem());
	public static final RegistryObject<Item> ORBERED = REGISTRY.register("orbered", () -> new OrberedItem());
	public static final RegistryObject<Item> ORBEYELLOW = REGISTRY.register("orbeyellow", () -> new OrbeyellowItem());
	public static final RegistryObject<Item> SKULLBLUE = REGISTRY.register("skullblue", () -> new SkullblueItem());
	public static final RegistryObject<Item> SKULLBROWN = REGISTRY.register("skullbrown", () -> new SkullbrownItem());
	public static final RegistryObject<Item> SKULLGREEN = REGISTRY.register("skullgreen", () -> new SkullgreenItem());
	public static final RegistryObject<Item> SKULLGREY = REGISTRY.register("skullgrey", () -> new SkullgreyItem());
	public static final RegistryObject<Item> SKULLPURPLE = REGISTRY.register("skullpurple", () -> new SkullpurpleItem());
	public static final RegistryObject<Item> SKULLYELLOW = REGISTRY.register("skullyellow", () -> new SkullyellowItem());
	public static final RegistryObject<Item> SKULLRED = REGISTRY.register("skullred", () -> new SkullredItem());
	public static final RegistryObject<Item> TREBOL = REGISTRY.register("trebol", () -> new TrebolItem());
	public static final RegistryObject<Item> INFINITYSWORDBALANCED = REGISTRY.register("infinityswordbalanced", () -> new InfinityswordbalancedItem());
	public static final RegistryObject<Item> INFINITYSWORD_1 = REGISTRY.register("infinitysword_1", () -> new Infinitysword1Item());
	public static final RegistryObject<Item> INFINITY_1PICK = REGISTRY.register("infinity_1pick", () -> new Infinity1pickItem());
	public static final RegistryObject<Item> ABSOLUTE_PLATE = REGISTRY.register("absolute_plate", () -> new AbsolutePlateItem());
	public static final RegistryObject<Item> CACOTA = REGISTRY.register("cacota", () -> new CacotaItem());
	public static final RegistryObject<Item> GALAXY_POP_NADIEN = block(GalaxyCoreModBlocks.GALAXY_POP_NADIEN);
	public static final RegistryObject<Item> FUNKITO_NADIEN = block(GalaxyCoreModBlocks.FUNKITO_NADIEN);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
